### ISSUE TITLE
API to get the meta-data of Greyhound server

### ISSUE THREAD

**Issue by gbivins** [hobu/greyhound#46]
Greyhound is pretty awesome! I'm attempting to understand how I can go about writing a new client for it but I ran into a snag.  If I know the location of a greyhound server, I would like to be able to query things about the server without having to query the actual data it's serving. For instance, how do I know what point clouds are being hosted there? Is there an API to query things like:
   - Is greyhound running/active?   `greyhound:8080/status`  
   - list the point clouds greyhound is aware of so the <resource> parameter can be queried and 
      at runtime? `greyhound:8080/point-clouds` 

Is there an existing API like this? I looked at the js file and didn't see anything obvious but I'm not
all that familiar with js app dev.

**Comment by connormanning** [comment]
There's currently no capability for listing available resources within Greyhound (although it has long been requested - see #26).  It's feasible that it could be added, although I'm unsure how it should work if Greyhound were configured with [external authentication](https://github.com/hobu/greyhound/blob/master/doc/administration.rst#authentication-settings), in which case you wouldn't really want to expose all of the available resource names.  The current mindset is that people building applications around Greyhound would build this functionality into their application rather than Greyhound itself.

**Comment by gbivins** [comment]
Ok. So my "indexed" data resides somewhere known and I point greyhound at it. My app would use some other API/service that knows more info about the "indexed" data to get the meta data I'm interested in. Am I thinking about this correctly now?

**Comment by connormanning** [comment]
Yes that's the current model.  If you can, feel free to share some information about your application - it always helps to know how people are using things for decisions going forward.

**Comment by gbivins** [comment]
I'm basically trying to set this up on a cluster backed by AWS via [dcos ](https://dcos.io/).  
Now that I have a better idea of the intended use of greyhound, I think my real problems are with the entwine setup/config.
